---

<img src="https://user-images.githubusercontent.com/7065401/39118512-dfa1cc1a-46e9-11e8-9547-093d4532451e.png"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Introduction to Pandas DataFrames

Probably the most important data structure of pandas is the `DataFrame`. It's a tabular structure tightly integrated with `Series`.

A DataFrame is a tabular structure with the following properties:

- It's composed by a ordered series of rows and a ordered series of columns.
- It also uses an index to reference individual rows.
- Each column could have a different NumPy-related type.
- It could be seen as a collection of multiple of Series, all sharing the same index.
- Can be "sliced" horizontally (per row) or vertically (per column).

In [25]:
import numpy as np
import pandas as pd



## DataFrames creation

The `DataFrame` constructor accepts the following parameters:

- **data**: (required) has all the data we want to store on the DataFrame and could be a Series dictionary, a sequences dictionary, a bidimensional ndarray, a Series or another DataFrame.
- **index**: (optional), has all the labels we want to assign to the rows of our DatFrame and could be a Python sequence or an unidimensional ndarray. Default value: `np.arange(0, len(rows))`.
- **columns**: (optional), has all the labels we want to assign to the columns of our DatFrame and could be a Python sequence or an unidimensional ndarray. Default value: `np.arange(0, len(columns))`.
- **dtype**: (optional) any NumPy data type to be assigned on columns.

In [26]:
# Using a dictionary of sequences
dataframe = pd.DataFrame({'col1': [1, 2, 3],
                          'col2': ['one', 'two', 'three'],
                          'col3': [1.0, 2.0, 3.0]})

dataframe

   col1   col2  col3
0     1    one   1.0
1     2    two   2.0
2     3  three   3.0

In [27]:
# Using a dictionary of Series
dataframe = pd.DataFrame({'var1': pd.Series([1, 2, 3], dtype=float),
                          'var2': pd.Series(['a', 'b'])})

dataframe

   var1 var2
0   1.0    a
1   2.0    b
2   3.0  NaN

In [28]:
# Using a ndarray with indexes to rows and columns
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4),
                         index=['r1', 'r2', 'r3', 'r4'],
                         columns=['c1', 'c2', 'c3', 'c4'])
dataframe

    c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [29]:
# Using a ndarray with indexes to rows and columns, with fixed type
dataframe = pd.DataFrame(np.arange(16).reshape(4,4), dtype=np.int32)

dataframe

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [30]:
dataframe.dtypes

0    int32
1    int32
2    int32
3    int32
dtype: object

---

## DataFrame elements

`DataFrame`s expose some useful attributes:

In [31]:
dataframe = pd.DataFrame({'col1': pd.Series([1, 2, 3], dtype=np.float64),
                          'col2': pd.Series(['a', 'b'])})

dataframe

   col1 col2
0   1.0    a
1   2.0    b
2   3.0  NaN

In [32]:
# Show first rows of our DataFrame
dataframe.head()

   col1 col2
0   1.0    a
1   2.0    b
2   3.0  NaN

In [33]:
# Type of our DataFrame columns
dataframe.dtypes

col1    float64
col2     object
dtype: object

In [34]:
dataframe

   col1 col2
0   1.0    a
1   2.0    b
2   3.0  NaN

In [35]:
# Values of a DataFrame
dataframe.values

array([[1.0, 'a'],
       [2.0, 'b'],
       [3.0, nan]], dtype=object)

In [36]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      float64
 1   col2    2 non-null      object
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes

In [37]:
type(dataframe.values)

numpy.ndarray

In [38]:
# Using a ndarray with indexes to rows and columns
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4),
                         index=['r1', 'r2', 'r3', 'r4'],
                         columns=['c1', 'c2', 'c3', 'c4'])
dataframe

    c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [39]:
# Index of a DataFrame
dataframe.index

Index(['r1', 'r2', 'r3', 'r4'], dtype='object')

In [40]:
# Columns of a DataFrame
dataframe.columns

Index(['c1', 'c2', 'c3', 'c4'], dtype='object')

In [41]:
# Dimension of the DataFrame
dataframe.ndim # two dimensions for table (vertical, horizontal)

2

In [42]:
# Shape of the DataFrame
dataframe.shape

(4, 4)

In [43]:
# Number of DataFrame elements
dataframe.size

16

> _Indexes are immutable, so we can't change individual values independently. However, we can change a complete index with a new index._

In [44]:
dataframe = pd.DataFrame({'var1': pd.Series([1, 2, 3], dtype=np.float64),
                          'var2': pd.Series(['a', 'b'])})

dataframe

   var1 var2
0   1.0    a
1   2.0    b
2   3.0  NaN

In [45]:
# Modifying a row index will give us an error
dataframe.index[0] = 4

TypeError: Index does not support mutable operations

In [ ]:
# Modifying a column index will give us an error
dataframe.columns[0] = 4

TypeError: Index does not support mutable operations

In [ ]:
# This will work
dataframe.index = ['r1', 'r2', 'r3']
dataframe

    var1 var2
r1   1.0    a
r2   2.0    b
r3   3.0  NaN

In [ ]:
# This will work
dataframe.columns = ['c1', 'c2']
dataframe

     c1   c2
r1  1.0    a
r2  2.0    b
r3  3.0  NaN


---
###  Note:
> In this class, we introduced only the fundamentals of Pandas to build Series and DataFrames, due to time limitations, many important Pandas functionalities and techniques were not covered. 

#### These include:

- Data cleaning and preprocessing
- Handling missing values
- Detecting and correcting invalid values
- Converting and managing incorrect data types
- Removing duplicate data
- Filtering data using conditional statements
- Boolean indexing and boolean filtering
- String manipulation and text processing
- Date and time handling
- Merging and combining tables
- Grouping and aggregation techniques
- Inner joins and outer joins
- Creating and analyzing pivot tables

Additional resources for data manipulation:
- [Python for Data Analysis](https://github.com/SamaherAlzhrani/Python_Programming_Fundamentals_for_Deep_Learning/blob/main/Python_for_Data_Analysis.pdf)
- [Python for Data Science the Ultimate Beginners Guide](https://github.com/SamaherAlzhrani/Python_Programming_Fundamentals_for_Deep_Learning/blob/main/Python_for_Data_Science_the_Ultimate_Beginners_Guide-.pdf)